[build]
edge_functions = "./netlify/edge-functions"
publish = "."
publishOrigin = "default"
functions = "./netlify/functions"

[functions]
  directory = "./netlify/functions/"

[[redirects]]
  from = "/f/*"
  to = "/.netlify/functions/:splat"
  status = 200