[build]
edge_functions = "./netlify/edge-functions"
publish = "."
publishOrigin = "default"
functions = "./netlify/functions"
command = "make build"

[build.environment]
  GO_IMPORT_PATH = "github.com/jakechampion/tricks"

[functions]
  directory = "./netlify/functions/"

[[redirects]]
  from = "/f/*"
  to = "/.netlify/functions/:splat"
  status = 200
